"use client";

import { FormEvent, useEffect, useState } from "react";

type Request = { id: string; status: string; purchase_request_items: Array<{ requested_quantity: number; materials: { code: string; name: string; unit: string } }> };
type Supplier = { id: string; legal_name: string; trade_name: string | null };
const initialForm = { requestId: "", supplierId: "", unitPrice: "", freight: "", deliveryDays: "", paymentTerms: "", notes: "" };

export default function QuotesPage() {
  const [requests, setRequests] = useState<Request[]>([]); const [suppliers, setSuppliers] = useState<Supplier[]>([]); const [form, setForm] = useState(initialForm); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch("/api/quotes", { cache: "no-store" }).then(async (response) => { const result = (await response.json()) as { requests?: Request[]; suppliers?: Supplier[]; error?: string }; if (!response.ok) throw new Error(result.error ?? "Não foi possível carregar as opções."); setRequests(result.requests ?? []); setSuppliers(result.suppliers ?? []); }).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)); }, []);
  function update(field: keyof typeof initialForm, value: string) { setForm((current) => ({ ...current, [field]: value })); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setMessage(""); setSaving(true); const response = await fetch("/api/quotes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, unitPrice: Number(form.unitPrice), freight: Number(form.freight || 0), deliveryDays: Number(form.deliveryDays || 0) }) }); const result = (await response.json()) as { error?: string }; if (!response.ok) setError(result.error ?? "Não foi possível registrar a cotação."); else { setMessage("Cotação registrada com sucesso."); setForm(initialForm); } setSaving(false); }
  return <main className="materials-page"><header className="materials-header"><div><a className="back-link" href="/">← Voltar ao resumo</a><p className="eyebrow">COMPARAÇÃO DE FORNECEDORES</p><h1>Nova cotação</h1><p className="subtitle">Registre preço, frete e prazo para uma solicitação.</p></div><div className="top-avatar">MC</div></header><section className="panel request-panel"><div className="panel-heading"><div><h2>Dados da cotação</h2><p>A solicitação passará para o status cotado.</p></div></div><form className="material-form request-form" onSubmit={submit}><label>Solicitação de compra<select value={form.requestId} onChange={(event) => update("requestId", event.target.value)} required><option value="">Selecione uma solicitação</option>{requests.map((request) => { const item = request.purchase_request_items[0]; return <option key={request.id} value={request.id}>{item?.materials.code} · {item?.materials.name} · {item?.requested_quantity} {item?.materials.unit}</option>; })}</select></label><label>Fornecedor<select value={form.supplierId} onChange={(event) => update("supplierId", event.target.value)} required><option value="">Selecione um fornecedor</option>{suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.trade_name || supplier.legal_name}</option>)}</select></label><div className="form-row"><label>Preço unitário<input type="number" min="0" step="0.01" value={form.unitPrice} onChange={(event) => update("unitPrice", event.target.value)} required /></label><label>Frete<input type="number" min="0" step="0.01" value={form.freight} onChange={(event) => update("freight", event.target.value)} placeholder="0,00" /></label></div><div className="form-row"><label>Prazo (dias)<input type="number" min="0" step="1" value={form.deliveryDays} onChange={(event) => update("deliveryDays", event.target.value)} /></label><label>Condição de pagamento<input value={form.paymentTerms} onChange={(event) => update("paymentTerms", event.target.value)} placeholder="Ex.: 28 dias" /></label></div><label>Observação<textarea value={form.notes} onChange={(event) => update("notes", event.target.value)} rows={3} /></label>{error && <p className="login-error" role="alert">{error}</p>}{message && <p className="success-message" role="status">{message}</p>}<button className="primary-button" type="submit" disabled={loading || saving}>{saving ? "Salvando..." : "Registrar cotação"}</button></form></section></main>;
}
