"use client";

import { FormEvent, useEffect, useState } from "react";

type Option = { id: string; name: string; code?: string; unit?: string };
const initialForm = { projectId: "", materialId: "", quantity: "", priority: "normal", neededAt: "", estimatedUnitCost: "", notes: "" };

export default function PurchasesPage() {
  const [projects, setProjects] = useState<Option[]>([]);
  const [materials, setMaterials] = useState<Option[]>([]);
  const [form, setForm] = useState(initialForm);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  useEffect(() => { fetch("/api/movement-options", { cache: "no-store" }).then(async (response) => { const result = (await response.json()) as { projects?: Option[]; materials?: Option[]; error?: string }; if (!response.ok) throw new Error(result.error ?? "Não foi possível carregar as opções."); setProjects(result.projects ?? []); setMaterials(result.materials ?? []); }).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)); }, []);
  function update(field: keyof typeof initialForm, value: string) { setForm((current) => ({ ...current, [field]: value })); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setMessage(""); setSaving(true); const response = await fetch("/api/purchases", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, quantity: Number(form.quantity), estimatedUnitCost: Number(form.estimatedUnitCost || 0) }) }); const result = (await response.json()) as { error?: string }; if (!response.ok) setError(result.error ?? "Não foi possível criar a solicitação."); else { setMessage("Solicitação de compra criada."); setForm(initialForm); } setSaving(false); }
  return <main className="materials-page"><header className="materials-header"><div><a className="back-link" href="/">← Voltar ao resumo</a><p className="eyebrow">PLANEJAMENTO DE COMPRAS</p><h1>Solicitação de compra</h1><p className="subtitle">Antecipe necessidades antes da ruptura do estoque.</p></div><div className="top-avatar">MC</div></header><section className="panel request-panel"><div className="panel-heading"><div><h2>Nova solicitação</h2><p>O pedido começa como pendente para análise de compras.</p></div></div><form className="material-form request-form" onSubmit={submit}><div className="form-row"><label>Obra<select value={form.projectId} onChange={(event) => update("projectId", event.target.value)} required><option value="">Selecione uma obra</option>{projects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Material<select value={form.materialId} onChange={(event) => update("materialId", event.target.value)} required><option value="">Selecione um material</option>{materials.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label></div><div className="form-row"><label>Quantidade<input type="number" min="0.001" step="0.001" value={form.quantity} onChange={(event) => update("quantity", event.target.value)} required /></label><label>Prioridade<select value={form.priority} onChange={(event) => update("priority", event.target.value)}><option value="urgent">Urgente</option><option value="normal">Normal</option><option value="scheduled">Programada</option></select></label></div><div className="form-row"><label>Custo estimado<input type="number" min="0" step="0.01" value={form.estimatedUnitCost} onChange={(event) => update("estimatedUnitCost", event.target.value)} placeholder="0,00" /></label><label>Necessário em<input type="date" value={form.neededAt} onChange={(event) => update("neededAt", event.target.value)} /></label></div><label>Observação<textarea value={form.notes} onChange={(event) => update("notes", event.target.value)} rows={3} placeholder="Motivo da compra ou contexto da necessidade" /></label>{error && <p className="login-error" role="alert">{error}</p>}{message && <p className="success-message" role="status">{message}</p>}<button className="primary-button" type="submit" disabled={loading || saving}>{saving ? "Enviando..." : "Enviar solicitação"}</button></form></section></main>;
}
