"use client";

import { FormEvent, useEffect, useState } from "react";

type Supplier = { id: string; legal_name: string; trade_name: string | null; document: string | null; email: string | null; phone: string | null };
const initialForm = { legalName: "", tradeName: "", document: "", email: "", phone: "" };

export default function SuppliersPage() {
  const [suppliers, setSuppliers] = useState<Supplier[]>([]);
  const [form, setForm] = useState(initialForm);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  async function load() { setLoading(true); const response = await fetch("/api/suppliers", { cache: "no-store" }); const result = (await response.json()) as { suppliers?: Supplier[]; error?: string }; setSuppliers(result.suppliers ?? []); if (!response.ok) setError(result.error ?? "Não foi possível carregar os fornecedores."); setLoading(false); }
  useEffect(() => { void load(); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setMessage(""); setSaving(true); const response = await fetch("/api/suppliers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const result = (await response.json()) as { error?: string }; if (!response.ok) setError(result.error ?? "Não foi possível cadastrar o fornecedor."); else { setMessage("Fornecedor cadastrado com sucesso."); setForm(initialForm); await load(); } setSaving(false); }
  return <main className="materials-page"><header className="materials-header"><div><a className="back-link" href="/">← Voltar ao resumo</a><p className="eyebrow">BASE DE COMPRAS</p><h1>Fornecedores</h1><p className="subtitle">Cadastre parceiros para comparar preços e prazos.</p></div><div className="top-avatar">MC</div></header><section className="materials-grid"><article className="panel material-form-panel"><div className="panel-heading"><div><h2>Novo fornecedor</h2><p>Dados de contato e identificação</p></div></div><form className="material-form" onSubmit={submit}><label>Razão social<input value={form.legalName} onChange={(event) => setForm({ ...form, legalName: event.target.value })} placeholder="Empresa fornecedora" required /></label><label>Nome fantasia<input value={form.tradeName} onChange={(event) => setForm({ ...form, tradeName: event.target.value })} placeholder="Opcional" /></label><label>CNPJ<input value={form.document} onChange={(event) => setForm({ ...form, document: event.target.value })} placeholder="00.000.000/0000-00" /></label><div className="form-row"><label>E-mail<input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label>Telefone<input value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></label></div>{error && <p className="login-error" role="alert">{error}</p>}{message && <p className="success-message" role="status">{message}</p>}<button className="primary-button" type="submit" disabled={saving}>{saving ? "Salvando..." : "Cadastrar fornecedor"}</button></form></article><article className="panel materials-list-panel"><div className="panel-heading"><div><h2>Fornecedores cadastrados</h2><p>{suppliers.length} parceiros visíveis para sua empresa</p></div><button className="select-button" type="button" onClick={() => void load()}>Atualizar ↻</button></div>{loading ? <p className="empty-state">Carregando...</p> : suppliers.length === 0 ? <p className="empty-state">Nenhum fornecedor cadastrado.</p> : <div className="materials-table-wrap"><table><thead><tr><th>RAZÃO SOCIAL</th><th>NOME FANTASIA</th><th>CNPJ</th><th>CONTATO</th></tr></thead><tbody>{suppliers.map((supplier) => <tr key={supplier.id}><td><strong>{supplier.legal_name}</strong></td><td>{supplier.trade_name || "-"}</td><td>{supplier.document || "-"}</td><td>{supplier.email || supplier.phone || "-"}</td></tr>)}</tbody></table></div>}</article></section></main>;
}
