"use client";

import { useEffect, useState } from "react";

type Order = { id: string; order_number: string; status: string; total_amount: number; suppliers: { legal_name: string; trade_name: string | null }; purchase_order_items: Array<{ quantity: number; materials: { name: string; code: string; unit: string } }> };
type Warehouse = { id: string; name: string }; type Location = { id: string; code: string; name: string; warehouse_id: string };
const statusLabels: Record<string, string> = { pending: "Pendente", approved: "Aprovado", sent: "Enviado", received: "Recebido", partial: "Parcial", cancelled: "Cancelado" };

export default function OrdersPage() { const [orders, setOrders] = useState<Order[]>([]); const [warehouses, setWarehouses] = useState<Warehouse[]>([]); const [locations, setLocations] = useState<Location[]>([]); const [warehouseId, setWarehouseId] = useState(""); const [locationId, setLocationId] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true); const [working, setWorking] = useState("");
  async function load() { setLoading(true); const [ordersResponse, optionsResponse] = await Promise.all([fetch("/api/purchase-orders", { cache: "no-store" }), fetch("/api/movement-options", { cache: "no-store" })]); const orderResult = (await ordersResponse.json()) as { orders?: Order[]; error?: string }; const options = (await optionsResponse.json()) as { warehouses?: Warehouse[]; locations?: Location[] }; setOrders(orderResult.orders ?? []); setWarehouses(options.warehouses ?? []); setLocations(options.locations ?? []); if (!ordersResponse.ok) setError(orderResult.error ?? "Não foi possível carregar os pedidos."); setLoading(false); }
  useEffect(() => { void load(); }, []); const availableLocations = locations.filter((location) => location.warehouse_id === warehouseId);
  async function action(orderId: string, actionName: string) { setWorking(`${orderId}-${actionName}`); setError(""); setMessage(""); const response = await fetch("/api/purchase-orders", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ orderId, action: actionName, warehouseId, locationId }) }); const result = (await response.json()) as { error?: string }; if (!response.ok) setError(result.error ?? "Ação recusada."); else { setMessage("Pedido atualizado com sucesso."); await load(); } setWorking(""); }
  return <main className="materials-page"><header className="materials-header"><div><a className="back-link" href="/">← Voltar ao resumo</a><p className="eyebrow">CICLO DE COMPRAS</p><h1>Pedidos de compra</h1><p className="subtitle">Aprove, envie e receba pedidos vinculados ao estoque.</p></div><div className="top-avatar">MC</div></header><section className="panel separation-controls no-print"><div className="material-form form-row"><label>Almoxarifado para recebimento<select value={warehouseId} onChange={(event) => { setWarehouseId(event.target.value); setLocationId(""); }}><option value="">Selecione quando receber</option>{warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</select></label><label>Local de recebimento<select value={locationId} onChange={(event) => setLocationId(event.target.value)}><option value="">Selecione o local</option>{availableLocations.map((location) => <option key={location.id} value={location.id}>{location.code} · {location.name}</option>)}</select></label></div></section>{error && <p className="login-error" role="alert">{error}</p>}{message && <p className="success-message" role="status">{message}</p>}{loading ? <p className="empty-state">Carregando pedidos...</p> : orders.length === 0 ? <div className="panel empty-panel"><p className="empty-state">Nenhum pedido criado.</p></div> : <section className="approval-list">{orders.map((order) => <article className="panel request-card" key={order.id}><div className="request-card-top"><div><span className="priority-tag normal">{statusLabels[order.status] ?? order.status}</span><h2>{order.order_number}</h2><p>{order.suppliers.trade_name || order.suppliers.legal_name} · {order.purchase_order_items[0]?.materials.name}</p></div><div className="order-actions">{order.status === "pending" && <button className="select-button" type="button" disabled={working === `${order.id}-approve`} onClick={() => void action(order.id, "approve")}>Aprovar</button>}{order.status === "approved" && <button className="select-button" type="button" disabled={working === `${order.id}-send`} onClick={() => void action(order.id, "send")}>Enviar</button>}{(order.status === "approved" || order.status === "sent") && <button className="primary-button" type="button" disabled={!warehouseId || !locationId || working === `${order.id}-receive`} onClick={() => void action(order.id, "receive")}>Receber</button>}</div></div><div className="request-meta"><span>Total <strong>R$ {Number(order.total_amount).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}</strong></span><span>Item <strong>{order.purchase_order_items[0]?.quantity} {order.purchase_order_items[0]?.materials.unit}</strong></span><span>Status <strong>{statusLabels[order.status] ?? order.status}</strong></span></div></article>)}</section>}</main>; }
