"use client";

import { useEffect, useMemo, useState } from "react";

type Balance = { quantity: number; reserved_quantity: number; materials: { code: string; name: string; unit: string; minimum_stock: number; average_cost: number; status: string }; warehouses: { name: string }; locations: { code: string; name: string } };

export default function StockReportPage() {
  const [balances, setBalances] = useState<Balance[]>([]);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  useEffect(() => { fetch("/api/reports/stock", { cache: "no-store" }).then(async (response) => { const result = (await response.json()) as { balances?: Balance[]; error?: string }; if (!response.ok) throw new Error(result.error ?? "Não foi possível gerar o relatório."); setBalances(result.balances ?? []); }).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)); }, []);
  const totals = useMemo(() => balances.reduce((summary, balance) => ({ items: summary.items + Number(balance.quantity), value: summary.value + Number(balance.quantity) * Number(balance.materials.average_cost), critical: summary.critical + (Number(balance.quantity) < Number(balance.materials.minimum_stock) ? 1 : 0) }), { items: 0, value: 0, critical: 0 }), [balances]);
  return <main className="materials-page report-page"><header className="materials-header"><div><a className="back-link no-print" href="/">← Voltar ao resumo</a><p className="eyebrow">RELATÓRIO OPERACIONAL</p><h1>Posição de estoque</h1><p className="subtitle">Saldo, reserva, localização e valor dos materiais.</p></div><div className="report-actions no-print"><button className="select-button" type="button" onClick={() => window.print()}>Imprimir / salvar PDF</button><div className="top-avatar">MC</div></div></header>{error && <p className="login-error" role="alert">{error}</p>}{loading ? <p className="empty-state">Gerando relatório...</p> : <><section className="report-summary"><div><span>Itens em saldo</span><strong>{totals.items.toLocaleString("pt-BR")}</strong></div><div><span>Valor estimado</span><strong>R$ {totals.value.toLocaleString("pt-BR", { minimumFractionDigits: 2 })}</strong></div><div><span>Abaixo do mínimo</span><strong>{totals.critical}</strong></div></section><section className="panel report-panel"><div className="panel-heading"><div><h2>Materiais por localização</h2><p>Gerado em {new Date().toLocaleString("pt-BR")}</p></div></div><div className="materials-table-wrap"><table><thead><tr><th>CÓDIGO</th><th>MATERIAL</th><th>LOCAL</th><th>SALDO</th><th>RESERVADO</th><th>MÍNIMO</th><th>VALOR</th><th>STATUS</th></tr></thead><tbody>{balances.length === 0 ? <tr><td colSpan={8} className="muted">Nenhum saldo encontrado.</td></tr> : balances.map((balance, index) => { const low = Number(balance.quantity) < Number(balance.materials.minimum_stock); return <tr key={`${balance.materials.code}-${balance.locations.code}-${index}`}><td><strong>{balance.materials.code}</strong></td><td>{balance.materials.name}</td><td>{balance.warehouses.name} · {balance.locations.code}</td><td>{balance.quantity} {balance.materials.unit}</td><td>{balance.reserved_quantity}</td><td>{balance.materials.minimum_stock}</td><td>R$ {(Number(balance.quantity) * Number(balance.materials.average_cost)).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}</td><td><span className={`status-tag ${low ? "low" : ""}`}>{low ? "Atenção" : "Normal"}</span></td></tr>; })}</tbody></table></div></section></>}</main>;
}
