"use client";

import { useEffect, useMemo, useState } from "react";

type Project = { id: string; name: string };
type Movement = { type: "issue" | "loss"; quantity: number; unit_cost: number; created_at: string; materials: { code: string; name: string; unit: string }; projects: { name: string } };
type Summary = { code: string; name: string; unit: string; issue: number; loss: number; value: number };

export default function ConsumptionReportPage() {
  const [projects, setProjects] = useState<Project[]>([]);
  const [movements, setMovements] = useState<Movement[]>([]);
  const [filters, setFilters] = useState({ projectId: "", from: "", to: "" });
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  useEffect(() => { fetch("/api/movement-options", { cache: "no-store" }).then((response) => response.json()).then((result: { projects?: Project[] }) => setProjects(result.projects ?? [])).catch(() => setError("Não foi possível carregar as obras.")); }, []);
  async function loadReport() { setLoading(true); setError(""); const query = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value) query.set(key, value); }); const response = await fetch(`/api/reports/consumption?${query}`, { cache: "no-store" }); const result = (await response.json()) as { movements?: Movement[]; error?: string }; if (!response.ok) setError(result.error ?? "Não foi possível gerar o relatório."); else setMovements(result.movements ?? []); setLoading(false); }
  const summaries = useMemo(() => { const map = new Map<string, Summary>(); movements.forEach((movement) => { const current = map.get(movement.materials.code) ?? { code: movement.materials.code, name: movement.materials.name, unit: movement.materials.unit, issue: 0, loss: 0, value: 0 }; current[movement.type] += Number(movement.quantity); current.value += Number(movement.quantity) * Number(movement.unit_cost); map.set(movement.materials.code, current); }); return [...map.values()].sort((a, b) => b.value - a.value); }, [movements]);
  const totalIssue = summaries.reduce((total, item) => total + item.issue, 0); const totalLoss = summaries.reduce((total, item) => total + item.loss, 0); const totalValue = summaries.reduce((total, item) => total + item.value, 0);
  function exportCsv() { const lines = ["Código,Material,Consumo,Perdas,Valor", ...summaries.map((item) => [item.code, item.name, item.issue, item.loss, item.value.toFixed(2)].join(","))]; const blob = new Blob([lines.join("\n")], { type: "text/csv;charset=utf-8" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "relatorio-consumo.csv"; link.click(); URL.revokeObjectURL(link.href); }
  return <main className="materials-page report-page"><header className="materials-header"><div><a className="back-link no-print" href="/">← Voltar ao resumo</a><p className="eyebrow">ANÁLISE DE CONSUMO</p><h1>Consumo e perdas</h1><p className="subtitle">Entenda o que foi aplicado e o que virou perda.</p></div><div className="report-actions no-print"><button className="select-button" type="button" onClick={exportCsv}>Exportar CSV ↓</button><button className="select-button" type="button" onClick={() => window.print()}>Salvar PDF</button><div className="top-avatar">MC</div></div></header><section className="panel report-filters no-print"><div className="kardex-filters"><label>Obra<select value={filters.projectId} onChange={(event) => setFilters({ ...filters, projectId: event.target.value })}><option value="">Todas as obras</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label>De<input type="date" value={filters.from} onChange={(event) => setFilters({ ...filters, from: event.target.value })} /></label><label>Até<input type="date" value={filters.to} onChange={(event) => setFilters({ ...filters, to: event.target.value })} /></label><button className="select-button" type="button" onClick={() => void loadReport()}>Atualizar</button></div></section>{error && <p className="login-error" role="alert">{error}</p>}<section className="report-summary"><div><span>Consumo aplicado</span><strong>{totalIssue.toLocaleString("pt-BR")}</strong></div><div><span>Perdas</span><strong>{totalLoss.toLocaleString("pt-BR")}</strong></div><div><span>Valor movimentado</span><strong>R$ {totalValue.toLocaleString("pt-BR", { minimumFractionDigits: 2 })}</strong></div></section>{loading ? <p className="empty-state">Gerando relatório...</p> : <section className="panel report-panel"><div className="panel-heading"><div><h2>Resumo por material</h2><p>{movements.length} movimentos encontrados</p></div></div><div className="materials-table-wrap"><table><thead><tr><th>CÓDIGO</th><th>MATERIAL</th><th>CONSUMO</th><th>PERDAS</th><th>VALOR</th></tr></thead><tbody>{summaries.length === 0 ? <tr><td colSpan={5} className="muted">Clique em atualizar para consultar o período.</td></tr> : summaries.map((item) => <tr key={item.code}><td><strong>{item.code}</strong></td><td>{item.name}</td><td className="amount in">{item.issue} {item.unit}</td><td className="amount out">{item.loss} {item.unit}</td><td>R$ {item.value.toLocaleString("pt-BR", { minimumFractionDigits: 2 })}</td></tr>)}</tbody></table></div></section>}</main>;
}
