"use client";

import { useEffect, useState } from "react";

type Quote = { id: string; purchase_request_id: string; supplier_id: string; freight: number; delivery_days: number | null; payment_terms: string | null; suppliers: { legal_name: string; trade_name: string | null }; purchase_quote_items: Array<{ quantity: number; unit_price: number; materials: { code: string; name: string; unit: string } }> };

export default function CompareQuotesPage() {
  const [quotes, setQuotes] = useState<Quote[]>([]); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true); const [selecting, setSelecting] = useState("");
  async function load() { setLoading(true); const response = await fetch("/api/quotes/compare", { cache: "no-store" }); const result = (await response.json()) as { quotes?: Quote[]; error?: string }; setQuotes(result.quotes ?? []); if (!response.ok) setError(result.error ?? "Não foi possível carregar as cotações."); setLoading(false); }
  useEffect(() => { void load(); }, []);
  async function selectQuote(id: string) { setSelecting(id); setError(""); setMessage(""); const response = await fetch("/api/quotes/compare", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ quoteId: id }) }); const result = (await response.json()) as { error?: string }; if (!response.ok) setError(result.error ?? "Seleção recusada."); else { setMessage("Cotação selecionada e pedido criado."); await load(); } setSelecting(""); }
  return <main className="materials-page"><header className="materials-header"><div><a className="back-link" href="/">← Voltar ao resumo</a><p className="eyebrow">DECISÃO DE COMPRAS</p><h1>Comparar cotações</h1><p className="subtitle">Escolha a melhor condição e gere o pedido ao fornecedor.</p></div><div className="top-avatar">MC</div></header>{error && <p className="login-error" role="alert">{error}</p>}{message && <p className="success-message" role="status">{message}</p>}{loading ? <p className="empty-state">Carregando cotações...</p> : quotes.length === 0 ? <div className="panel empty-panel"><p className="empty-state">Nenhuma cotação pendente de seleção.</p></div> : <section className="approval-list">{quotes.map((quote) => { const item = quote.purchase_quote_items[0]; const total = Number(quote.freight) + Number(item?.quantity ?? 0) * Number(item?.unit_price ?? 0); return <article className="panel request-card quote-card" key={quote.id}><div className="request-card-top"><div><span className="priority-tag normal">Cotação</span><h2>{quote.suppliers.trade_name || quote.suppliers.legal_name}</h2><p>{item?.materials.code} · {item?.materials.name} · {item?.quantity} {item?.materials.unit}</p></div><button className="primary-button" type="button" disabled={selecting === quote.id} onClick={() => void selectQuote(quote.id)}>{selecting === quote.id ? "Gerando..." : "Selecionar"}</button></div><div className="request-meta"><span>Total <strong>R$ {total.toLocaleString("pt-BR", { minimumFractionDigits: 2 })}</strong></span><span>Entrega <strong>{quote.delivery_days ?? "Não informado"} dias</strong></span><span>Pagamento <strong>{quote.payment_terms || "Não informado"}</strong></span></div></article>; })}</section>}</main>;
}
